site_name: Nikiforova Kyunney, K33402

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Знакомство: index.md
 - Лабораторная работа №1: lab1.md
 - Лабораторная работа №2: lab2.md