site_name: My Docs
site_name: Alekseev Paul, K33421

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Знакомство: index.md
 - Лабораторная работа №1: lr1.md